// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmWil1R1QCE9KeBxQeJQ_G3sbXRMliVhA',
    appId: '1:924655811023:web:4493da2855b5f3a594baba',
    messagingSenderId: '924655811023',
    projectId: 'ai-image-generator-d5aee',
    authDomain: 'ai-image-generator-d5aee.firebaseapp.com',
    databaseURL: 'https://ai-image-generator-d5aee-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ai-image-generator-d5aee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5bmnbnn3POgk6gv1r7fvZfLbQfntKwlo',
    appId: '1:924655811023:android:9dd220120c17197f94baba',
    messagingSenderId: '924655811023',
    projectId: 'ai-image-generator-d5aee',
    databaseURL: 'https://ai-image-generator-d5aee-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ai-image-generator-d5aee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjPy0eMbLbxJckwd9he7r0fsLjZW-d_fg',
    appId: '1:924655811023:ios:ff721c672b86890094baba',
    messagingSenderId: '924655811023',
    projectId: 'ai-image-generator-d5aee',
    databaseURL: 'https://ai-image-generator-d5aee-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ai-image-generator-d5aee.appspot.com',
    iosBundleId: 'com.astral.aiImageGenerator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjPy0eMbLbxJckwd9he7r0fsLjZW-d_fg',
    appId: '1:924655811023:ios:1da22462de52ec1f94baba',
    messagingSenderId: '924655811023',
    projectId: 'ai-image-generator-d5aee',
    databaseURL: 'https://ai-image-generator-d5aee-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ai-image-generator-d5aee.appspot.com',
    iosBundleId: 'com.astral.aiImageGenerator.RunnerTests',
  );
}
